### PR TITLE
W-8129763: Add tabs component to the Requirement record page to fix heading structure

### PR DESCRIPTION
**Pull request by andrea-fernandez**
WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008fyuBIAQ/view

# Dev Changes

Added tabs component to the Requirement record page, and placed the Detail Panel inside the Detail tab, and the Related Lists component inside the Related tab. This fixes the heading structure issue we had, as now the heading structure is logically nested (H1 > H2 > H3).

# Critical Changes

# Changes

Added the **Tabs** component to the **Requirement** object **record page**, and placed the **Detail Panel** inside the **Detail tab**, and the **Related Lists** component inside the **Related tab**. This will improve the accessibility for this record page.

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
Refer to [Definition of Done](https://salesforce.quip.com/9P7hAOPHJJyU) to see any additional details for the items below:
~~- [ ] Any net new LWC work has JEST test coverage 50% or above~~
~~- [ ] Default Sa11y tests pass for all LWC components~~
~~- [ ] 🔒 Secure both Front-end (LWC) & back-end (Apex) as necessary~~
~~- [ ] 🔑 Grant users access in Permission Sets (Object, Field, Apex Class) as necessary~~
- [x] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: [W-0000000: Work Name]()
- [x] Make sure that ACs are updated (if any gaps)
- [ ] **All acceptance criteria have been met**
    - [x] Developer
    - [ ] Code Reviewer
    - [x] Pull Request contains draft release notes
    - [ ] Labels, help text, and customer facing messages are reviewed by Docs
- [ ] QE story level testing completed

### CODE REVIEW

**Comment by andrea-fernandez** [comment]
WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008fyuBIAQ/view

**Comment by andrea-fernandez** [comment]
image

**Comment by andrea-fernandez** [comment]
image

**Comment by nicolersmith** [comment]
@andrea-fernandez Can you tag Aaron instead on this so he can get used to the PR approval process?

**Comment by andrea-fernandez** [comment]
> @andrea-fernandez Can you tag Aaron instead on this so he can get used to the PR approval process? Thanks!

Hi! I did try that, but he doesn't appear when I search for his name. That's why I tagged you instead.

**Review by spelak-salesforce — APPROVED** [review]
Great work @andrea-fernandez !

**Pull request merged**
